### ISSUE TITLE
setting 'paths' in json sourcefile doesn't work correctly

### ISSUE THREAD

**Issue by ericbrook** [ebullient/json5e-convert-cli#11]
Version: 1.0.11
Using the attached json-files:

1) When using paths.json with the following command:
`5e-convert.cmd --index -o iwd2 -s SCAG .\5etools-mirror-1.github.io\data .\paths.json`
All output (deities, items, races... and tables and variant-rules) is put in the directory `z_rules`. There is no compendium directory.

1) When using paths2.json with the following command:
`5e-convert.cmd --index -o iwd2 -s SCAG .\5etools-mirror-1.github.io\data .\paths.json`
All rules are in the directory `z_rules`. (correct)
The compendium entry in the json file is ignored and instead, it created a `rules` directory and put all deities, items, etc there.

In both cases though, the deity files that refer to an image do so using the paths that were requested in the json-file.
eg
```
# Cyric
*Source: Sword Coast Adventurer's Guide p. 21* 
![](/z_Compendium/deities/img/symbol-of-cyric.jpg#symbol) 
```

[paths2.zip](https://github.com/ebullient/json5e-convert-cli/files/9614916/paths2.zip)

**Comment by ebullient** [comment]
Do you have the latest? What is the output of `5e-convert.cmd -V` ?

**Comment by ericbrook** [comment]
D:\Temp\test>5e-convert.cmd -V
5e-convert version 1.0.11

**Comment by Bugmaniac71** [comment]
I second this - I'd like to move the markdown files anywhere in my vault. I can't at the mo as there's always a root / put onto the paths (especially the bestiary).

Also would be a good idea if we can specify paths for all other items too (so we can customise them to exactly our vault and the links would all still work.)

**Comment by ebullient** [comment]
@ericbrook is my hero. He found/squashed it. ;)
