### ISSUE TITLE
-s=ALL now getting "Source DoSI is unknown"

### ISSUE THREAD

**Issue by Bugmaniac71** [ebullient/json5e-convert-cli#16]
-s=ALL now getting "Source DoSI is unknown"

Have the latest dataset from 5eTools and DOSI definately exists in there - Any ideas please?

R.

**Comment by ebullient** [comment]
Fancy a quick PR to add here: https://github.com/ebullient/json5e-convert-cli/blob/f47292d0e8c5bb733736dfdb361dceef4a99a9c8/src/main/java/dev/ebullient/json5e/tools5e/CompendiumSources.java#L149 ?

**Comment by ebullient** [comment]
Also: things should still render, but DoSI won't be expanded to a nice name.

**Comment by Bugmaniac71** [comment]
Thanks, yes confirmed that content showing up just that annoying error lol.

**Comment by ebullient** [comment]
It may be annoying.. but it let me know that I have missing sources to go fix. ;)

**Comment by Bugmaniac71** [comment]
Fab tool by the way, especially the templates.

**Comment by Bugmaniac71** [comment]
Also I found a couple of spells that don't export correctly, best to log as
an issue?

**Comment by ebullient** [comment]
yes, please!
