### ISSUE TITLE
Import of Books with subtitles ":" break markdown.

### ISSUE THREAD

**Issue by Bugmaniac71** [ebullient/json5e-convert-cli#17]
It looks like the output from books which have a colon in the title break markdown when viewed in Obsidian. Fixed manually by changing the colon to "SPACE DASH SPACE" " - " so that they show up correctly.

Its and easy fix from our end but having to do that after every export is teadious.

I found this while checking the spell lists. The spells below are teh first ones that i came across with the issue and the text below them is how I fixed them.

Acid Stream:
	"Unearthed Arcana:"
	"Unearthed Arcana - "

Blade Of Disaster: 
	"Icewind Dale:"
	"Icewind Dale - "
	
Blade Of Disaster: Doesnt import Classes)
	
borrowed-knowledge
	"Strixhaven:"
	"Strixhaven - "
	
Gust:
	"Eberron: Rising"
	"Eberron - Rising"

Linked Glyphs
	"Adventures in the Forgotten Realms:"
	"Adventures in the Forgotten Realms - "

**Comment by ebullient** [comment]
I will double check how I am importing books, and how slugifying works. Colons should not break the universe.

Thank you for the report, will have a look.

**Comment by ebullient** [comment]
Ok. I found one thing that explains the missing classes (though I don't understand how your fix fixed it... )

"break markdown"

What exactly is broken? Are there any errors or warnings in the output?

**Comment by Bugmaniac71** [comment]
If there's a colon in the meta data in obsidian it breaks the front
matter.l displaying correctly...

**Comment by ebullient** [comment]
ok. Most things in the front matter should already be quoted and/or slugified.. but this is more specific. Thanks

**Comment by ebullient** [comment]
Do you have a custom template, by chance? I can not reproduce this. I don't have any colons in the metadata anywhere.

**Comment by Bugmaniac71** [comment]
Hiya, Yes custom template do for example below my custom Spell template
(also have custom monster template as well)
---
...
spell_name: Alter Self
spell_level: 2nd-level
spell_school: Transmutation
spell_ritual:
spell_cast_time: 1 action
spell_range: Self
spell_components: V, S
spell_duration: Concentration, up to 1 hour
spell_classes: Artificer, Druid (Moon), Sorcerer, Wizard
spell_source: Player's Handbook p. 211
---

![[Transmutation.png|60]]
# `=this.spell_name`
*`=this.spell_level`, `=this.spell_school` `=this.spell_ritual`*

----
- **Casting time:** `=this.spell_cast_time`
- **Range:** `=this.spell_range`
- **Components:** `=this.spell_components`
- **Duration:** `=this.spell_duration`



So my data is pulled through and pushed to Front Matter - that way you can
also use the Data View plugin to process the info as required.
And then in my actual template below that I reference the data with
`=this.spell_source" for instance. but if a source has a colon in teh title
(like Frostmaiden) then this functionality breaks.

Does that explain it a bit clearer?

C

**Comment by ebullient** [comment]
AH! This makes more sense! Can you surround the to-be-replaced value with quotes in the YAML metadata?
```
spell_name: "Alter Self"
```

Quotes are not always required, but in the face of potential messy characters, they can solve the problem.

Additionally: would you prefer sources as a list you can concatenate yourself, rather than as one pre-made string?

**Comment by Bugmaniac71** [comment]
Perfect! Added quotes aroud the data in teh template and now works perfectly, thank you!

spell_source: "{resource.source}"
