### ISSUE TITLE
Option to create filenames with spaces instead of dash

### ISSUE THREAD

**Issue by Bugmaniac71** [ebullient/json5e-convert-cli#18]
Option to create filenames with spaces instead of dash. This then enables auto links to just work when using Books and Adventures already converted to MD from other sources.

**Comment by ebullient** [comment]
Just replace `-` wit a space? Or avoid normalizing? All of the docs (with dashes in the file name) have aliases.. links should still just work.

Have an example of one that doesn't?

**Comment by Bugmaniac71** [comment]
Hi again;->
So, for example, if I'm writing a new note and need to reference the 'Arcane Weapon' (spell)

This is what I want:
"This is a test for [[arcane weapon]] some text...''

This is what I get if I want the link to work:
"[[arcane-weapon]] would link correctly and gives a preview in obsidian when CTRL+hovver".

"[[arcane weapon]] does not link."

If there's a space instead of the hyphen then text that already exists will just need backlinking or manually adding [[xxx]] to them for it to work.

Regards
C

**Comment by ebullient** [comment]
You're writing that manually or from an import? If writing.. `[[arcane`... should auto-complete to the alias. Just confirming the behavior..

**Comment by Bugmaniac71** [comment]
Nope ignore me - its me not knowing how the linking works sorry.

**Comment by Bugmaniac71** [comment]
ooo that would be very nice!

**Comment by ericbrook** [comment]
Looks like the brand new version v1.0.0 of Obsidian made this a bit more important. It has an option to display the note name at the top of the note. This setting can be switched off, but it's either on or off for the entire vault, you can't modify this on note (or directory) level. Maybe that's doable via a plugin, but I have no clue of it's possible.

In any case, if anyone would like to use that setting, it would look a ton prettier if note names used spaces and sentence case.

Current look:
![image](https://user-images.githubusercontent.com/68905838/195694611-b2cb46b5-808b-49aa-ab4f-75b7a4faf6d2.png)

Removing the double name is just a small modification in the template of course.

**Comment by ebullient** [comment]
I turn that setting off every single time. It only works for people that don't sanitize their file names. It's one thing for dashes vs. spaces.. it's another for mixed single/double quotes and colons and a lot of other things.

I see your point, but I'm not a fan.

**Comment by ericbrook** [comment]
Oh, I didn't know that the title could be hidden with some CSS. 

.json5e-item.inline-title {
  display: none;
}

**Comment by ebullient** [comment]
I've at included example css to hide the inline titles in the css sample.

**Comment by ebullient** [comment]
Chewing on this, and while I could try to change spaces to tabs.. I think the divergence from the nice alias title to the file name is going to get worse rather than better.

I am currently chasing my tail because some files are being overwritten (duplicates). The only way to avoid that is to start including the primary source in the file name (unless it is one of the foundational 3, I think). 

For file names, that will be ok, but you'll definitely want to use the alias for reference in text.

**Comment by Bugmaniac71** [comment]
I would close this for now - The alias works fine for now - just need to go through existing md book and relink.
