### ISSUE TITLE
Provide just the path for resource.image

### ISSUE THREAD

**Issue by ericbrook** [ebullient/json5e-convert-cli#19]
Currently `resource.image` returns an image. 
eg:
`![](/z_Compendium/deities/img/symbol-of-tempus.jpg#symbol)`

While this is logical, it makes it impossible to do any formatting on the image via a custom template.
If it just returned the path: `/z_Compendium/deities/img/symbol-of-tempus.jpg`, formatting can be done in the template, like this:

`
{#if resource.image}![symbol|200]({resource.image}){/if}
`

**Comment by ebullient** [comment]
good plan. ;)
