### ISSUE TITLE
Extract Deity information

### ISSUE THREAD

**Issue by ericbrook** [ebullient/json5e-convert-cli#4]
Please extract deity information as well.

**Comment by ebullient** [comment]
Should be good to go with [Release 1.0.7](https://github.com/ebullient/json5e-convert-cli/releases/tag/1.0.7)

**Comment by ericbrook** [comment]
Does not seem to work.
I updated to version 1.0.8,
then ran "5e-convert.cmd --index -v -s"`*" -o WF .\5etools-mirror-1.github.io\data
This did not produce any deity files. (output1)

Copied the deities.json from the data directory,
then ran "5e-convert.cmd --index -o tt -v -s"`*" deities.json"
This did not produce any deity files. (output2)

Tried again using a source known to contain at least one deity (MTF)
PS D:\Temp\test> 5e-convert.cmd --index -o tt -v -s MTF deities.json
Again, no luck.

The index-files DO contain the deities, so there's that. 

[out1.txt](https://github.com/ebullient/json5e-convert-cli/files/9605726/out1.txt)
[out2.txt](https://github.com/ebullient/json5e-convert-cli/files/9605727/out2.txt)
[tt-json.zip](https://github.com/ebullient/json5e-convert-cli/files/9605735/tt-json.zip)

**Comment by ebullient** [comment]
Give this a go... [1.0.9](https://github.com/ebullient/json5e-convert-cli/releases/tag/1.0.9)

```
jbang app install --name 5e-convert --force --fresh https://jitpack.io/dev/ebullient/json5e-convert-cli/1.0.9/json5e-convert-cli-1.0.9-runner.jar
```
